-- MySQL Script generated by MySQL Workbench
-- Mon Dec 11 01:48:16 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sudoku2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sudoku2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sudoku2` DEFAULT CHARACTER SET utf8 ;
USE `sudoku2` ;

-- -----------------------------------------------------
-- Table `sudoku2`.`final`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sudoku2`.`final` (
  `NumSudoku` INT(11) NULL DEFAULT NULL,
  `Fila` INT(11) NULL DEFAULT NULL,
  `Col` INT(11) NULL DEFAULT NULL,
  `Valor` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sudoku2`.`inicial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sudoku2`.`inicial` (
  `NumSudoku` INT(11) NULL DEFAULT NULL,
  `Fila` INT(11) NULL DEFAULT NULL,
  `Col` INT(11) NULL DEFAULT NULL,
  `Valor` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sudoku2`.`intermedia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sudoku2`.`intermedia` (
  `user` TEXT NULL DEFAULT NULL,
  `NumSudoku` INT(11) NULL DEFAULT NULL,
  `Fila` INT(11) NULL DEFAULT NULL,
  `Col` INT(11) NULL DEFAULT NULL,
  `Valor` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sudoku2`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sudoku2`.`login` (	
  `user` TEXT NOT NULL,
  `password` TEXT NOT NULL,
  primary key (user(250)))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


load data local infile "C:/Users/janto/Documents/NetBeansProjects/sudokuVersion/src/java/CreaYCargaBD/inicial.txt" into table `sudoku2`.`inicial`
fields terminated by ','
LINES terminated by '\n'
(NumSudoku, Fila, Col, Valor);

load data local infile "C:/Users/janto/Documents/NetBeansProjects/sudokuVersion/src/java/CreaYCargaBD/final.txt" into table `sudoku2`.`final`
fields terminated by ','
LINES terminated by '\n'
(NumSudoku, Fila, Col, Valor);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
